export type CollegeCourse = {
  name: string;
  duration: string;
  annualFees: number;
};

export type CollegeReview = {
  author: string;
  role: string;
  rating: number;
  year: number;
  comment: string;
};

export type College = {
  slug: string;
  name: string;
  location: string;
  state: string;
  ownership: "Public" | "Private";
  feesAnnual: number;
  rating: number;
  placementRate: number;
  medianPackageLpa: number;
  highestPackageLpa: number;
  establishedYear: number;
  exams: string[];
  tags: string[];
  overview: string;
  courses: CollegeCourse[];
  recruiters: string[];
  reviews: CollegeReview[];
};

export type CollegeQuery = {
  search?: string;
  location?: string;
  course?: string;
  maxFees?: number;
  page?: number;
  limit?: number;
};

export const colleges: College[] = [
  {
    slug: "nit-trichy",
    name: "National Institute of Technology, Trichy",
    location: "Tiruchirappalli",
    state: "Tamil Nadu",
    ownership: "Public",
    feesAnnual: 180000,
    rating: 4.7,
    placementRate: 91,
    medianPackageLpa: 12.4,
    highestPackageLpa: 42,
    establishedYear: 1964,
    exams: ["JEE Main"],
    tags: ["Top NIT", "Placements", "CSE"],
    overview: "A nationally respected engineering campus with strong industry outcomes, a compact academic culture, and a reputation for rigorous peer learning.",
    courses: [
      { name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 },
      { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 180000 },
      { name: "M.Tech Data Science", duration: "2 years", annualFees: 95000 },
    ],
    recruiters: ["Microsoft", "Amazon", "Adobe", "Goldman Sachs"],
    reviews: [
      { author: "Aarav S.", role: "Final year student", rating: 5, year: 2025, comment: "Excellent placement culture and a highly motivated peer group." },
      { author: "Nisha K.", role: "Alumni", rating: 4.8, year: 2024, comment: "Course load is intense, but the outcomes are worth it." },
    ],
  },
  { slug: "vit-vellore", name: "VIT Vellore", location: "Vellore", state: "Tamil Nadu", ownership: "Private", feesAnnual: 220000, rating: 4.5, placementRate: 88, medianPackageLpa: 9.8, highestPackageLpa: 56, establishedYear: 1984, exams: ["VITEEE", "JEE Main"], tags: ["Innovation", "Large campus", "Industry"], overview: "A large, modern university environment with broad course availability, active student clubs, and strong industry participation.", courses: [{ name: "B.Tech Information Technology", duration: "4 years", annualFees: 220000 }, { name: "B.Tech Artificial Intelligence and Data Science", duration: "4 years", annualFees: 225000 }, { name: "BBA", duration: "3 years", annualFees: 165000 }], recruiters: ["Cisco", "Qualcomm", "TCS", "Infosys"], reviews: [{ author: "Riya M.", role: "Third year student", rating: 4.4, year: 2025, comment: "The campus is active and the placement support is dependable." }, { author: "Karan P.", role: "Parent", rating: 4.3, year: 2024, comment: "Very structured admissions process and a wide range of programs." }] },
  { slug: "srm-chennai", name: "SRM Institute of Science and Technology", location: "Chennai", state: "Tamil Nadu", ownership: "Private", feesAnnual: 310000, rating: 4.3, placementRate: 84, medianPackageLpa: 8.2, highestPackageLpa: 41, establishedYear: 1985, exams: ["SRMJEEE", "JEE Main"], tags: ["AI", "Research", "Private university"], overview: "Known for broad program choice and strong engagement with emerging technology tracks, especially for students seeking flexibility.", courses: [{ name: "B.Tech Artificial Intelligence", duration: "4 years", annualFees: 310000 }, { name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 305000 }, { name: "MBA", duration: "2 years", annualFees: 220000 }], recruiters: ["Wipro", "Accenture", "Deloitte", "Cognizant"], reviews: [{ author: "Meera A.", role: "Student", rating: 4.2, year: 2025, comment: "Good infrastructure and enough options to explore multiple domains." }, { author: "Arjun V.", role: "Alumni", rating: 4.1, year: 2024, comment: "Best for students who want a large, active campus ecosystem." }] },
  { slug: "bits-pilani", name: "BITS Pilani", location: "Pilani", state: "Rajasthan", ownership: "Private", feesAnnual: 475000, rating: 4.8, placementRate: 94, medianPackageLpa: 16.2, highestPackageLpa: 60, establishedYear: 1964, exams: ["BITSAT"], tags: ["Premium", "Placements", "Research"], overview: "A premium engineering institution with deep alumni reach, intense academics, and consistently strong recruiter interest.", courses: [{ name: "B.E. Computer Science", duration: "4 years", annualFees: 475000 }, { name: "B.E. Electronics and Instrumentation", duration: "4 years", annualFees: 475000 }, { name: "M.Sc. Economics", duration: "5 years", annualFees: 390000 }], recruiters: ["Google", "Apple", "Microsoft", "Bain"], reviews: [{ author: "Sneha D.", role: "Final year student", rating: 4.9, year: 2025, comment: "The academic pressure is real, but the industry credibility is unmatched." }, { author: "Aman R.", role: "Alumni", rating: 4.8, year: 2024, comment: "A strong brand name that opens doors everywhere." }] },
  { slug: "anna-university-cce", name: "College of Engineering, Guindy", location: "Chennai", state: "Tamil Nadu", ownership: "Public", feesAnnual: 85000, rating: 4.4, placementRate: 87, medianPackageLpa: 7.6, highestPackageLpa: 28, establishedYear: 1794, exams: ["TNEA"], tags: ["Affordable", "Legacy", "Core engineering"], overview: "A historic public engineering school with strong value for money, a classic campus environment, and solid placement outcomes.", courses: [{ name: "B.E. Computer Science", duration: "4 years", annualFees: 85000 }, { name: "B.E. Mechanical Engineering", duration: "4 years", annualFees: 85000 }, { name: "M.E. Software Engineering", duration: "2 years", annualFees: 65000 }], recruiters: ["Zoho", "TCS", "Bosch", "L&T"], reviews: [{ author: "Priya T.", role: "Student", rating: 4.5, year: 2025, comment: "Great value for money and a respected brand in Tamil Nadu." }, { author: "Vignesh M.", role: "Alumni", rating: 4.4, year: 2024, comment: "An old campus, but still very relevant for core engineering." }] },
  { slug: "iiit-hyderabad", name: "IIIT Hyderabad", location: "Hyderabad", state: "Telangana", ownership: "Private", feesAnnual: 420000, rating: 4.9, placementRate: 96, medianPackageLpa: 18.4, highestPackageLpa: 65, establishedYear: 1998, exams: ["JEE Main", "UGEE"], tags: ["Research", "AI/ML", "Elite"], overview: "A research-intensive institute with exceptional computer science strength, competitive admissions, and high placement intensity.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 420000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 420000 }, { name: "MS by Research", duration: "2 years", annualFees: 250000 }], recruiters: ["Google", "Meta", "Nvidia", "Adobe"], reviews: [{ author: "Rohan I.", role: "Research scholar", rating: 5, year: 2025, comment: "One of the strongest computer science environments in India." }, { author: "Ananya S.", role: "Alumni", rating: 4.9, year: 2024, comment: "Small, intense, and incredibly rewarding academically." }] },
  { slug: "rvce-bengaluru", name: "RV College of Engineering", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 245000, rating: 4.6, placementRate: 89, medianPackageLpa: 10.1, highestPackageLpa: 34, establishedYear: 1963, exams: ["KCET", "COMEDK"], tags: ["Bengaluru", "Industry", "Strong ROI"], overview: "A well-known private engineering college with strong corporate access thanks to location and a consistent alumni network.", courses: [{ name: "B.E. Computer Science and Engineering", duration: "4 years", annualFees: 245000 }, { name: "B.E. Electronics and Communication Engineering", duration: "4 years", annualFees: 245000 }, { name: "B.E. Mechanical Engineering", duration: "4 years", annualFees: 245000 }], recruiters: ["Amazon", "Cisco", "SAP", "HP"], reviews: [{ author: "Divya N.", role: "Student", rating: 4.6, year: 2025, comment: "Very practical ecosystem with Bangalore advantage." }, { author: "Siddharth G.", role: "Alumni", rating: 4.5, year: 2024, comment: "Solid college if you want balanced academics and access to recruiters." }] },
  { slug: "nit-mandya", name: "National Institute of Technology, Mandya", location: "Mandya", state: "Karnataka", ownership: "Public", feesAnnual: 168000, rating: 4.2, placementRate: 79, medianPackageLpa: 8.9, highestPackageLpa: 35, establishedYear: 2012, exams: ["JEE Main"], tags: ["NIT", "Growing", "Placements"], overview: "A newer NIT with developing infrastructure and growing industry recognition.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 168000 }], recruiters: ["TCS", "Infosys", "HCL", "Tech Mahindra"], reviews: [{ author: "Vikram K.", role: "Student", rating: 4.1, year: 2025, comment: "Good campus but fewer placement opportunities compared to older NITs." }, { author: "Suresh M.", role: "Alumni", rating: 4.2, year: 2024, comment: "Steady growth in placements and industry reach." }] },
  { slug: "nit-rourkela", name: "National Institute of Technology, Rourkela", location: "Rourkela", state: "Odisha", ownership: "Public", feesAnnual: 175000, rating: 4.6, placementRate: 88, medianPackageLpa: 11.2, highestPackageLpa: 40, establishedYear: 1961, exams: ["JEE Main"], tags: ["Top NIT", "Mining", "Core Engineering"], overview: "A premier NIT with strong core engineering heritage and excellent placement records.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 175000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 175000 }, { name: "M.Tech Advanced Manufacturing Systems", duration: "2 years", annualFees: 90000 }], recruiters: ["Microsoft", "Amazon", "Bharat Petroleum", "Tata Steel"], reviews: [{ author: "Harsh P.", role: "Student", rating: 4.6, year: 2025, comment: "Strong placement record and good faculty support." }, { author: "Deepak T.", role: "Alumni", rating: 4.5, year: 2024, comment: "Excellent for core engineering; isolated location but worth it." }] },
  { slug: "iit-bombay", name: "Indian Institute of Technology, Bombay", location: "Bengaluru", state: "Maharashtra", ownership: "Public", feesAnnual: 180000, rating: 5.0, placementRate: 99, medianPackageLpa: 24.5, highestPackageLpa: 95, establishedYear: 1958, exams: ["JEE Main"], tags: ["Elite", "Top placement", "Research"], overview: "India's top engineering institute with world-class research facilities and highest placement packages.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey"], reviews: [{ author: "Arjun M.", role: "Student", rating: 5.0, year: 2025, comment: "The best engineering education in India with unmatched opportunities." }, { author: "Priya V.", role: "Alumni", rating: 5.0, year: 2024, comment: "Life-changing experience with doors open everywhere." }] },
  { slug: "iit-delhi", name: "Indian Institute of Technology, Delhi", location: "Delhi", state: "Delhi", ownership: "Public", feesAnnual: 180000, rating: 4.9, placementRate: 98, medianPackageLpa: 22.8, highestPackageLpa: 88, establishedYear: 1961, exams: ["JEE Main"], tags: ["Elite", "Research", "Top placements"], overview: "A leading IIT with strong academic rigor and exceptional placement outcomes.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Apple", "Microsoft", "Accenture"], reviews: [{ author: "Nikhil R.", role: "Student", rating: 4.9, year: 2025, comment: "Exceptional faculty and world-class infrastructure." }, { author: "Kavya S.", role: "Alumni", rating: 4.9, year: 2024, comment: "Perfect launchpad for global careers." }] },
  { slug: "manipal-university", name: "Manipal Institute of Technology", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 275000, rating: 4.5, placementRate: 85, medianPackageLpa: 10.5, highestPackageLpa: 38, establishedYear: 1957, exams: ["KCET", "Entrance"], tags: ["Bangalore", "Global", "Research"], overview: "A well-established private university with international collaborations and modern campus facilities.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 275000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 275000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 275000 }], recruiters: ["Bosch", "SAP", "Intel", "Cognizant"], reviews: [{ author: "Tanvi K.", role: "Student", rating: 4.5, year: 2025, comment: "Great infrastructure and international exposure." }, { author: "Anil C.", role: "Alumni", rating: 4.4, year: 2024, comment: "Good for global placements and internships." }] },
  { slug: "nit-warangal", name: "National Institute of Technology, Warangal", location: "Warangal", state: "Telangana", ownership: "Public", feesAnnual: 172000, rating: 4.5, placementRate: 85, medianPackageLpa: 10.3, highestPackageLpa: 36, establishedYear: 1959, exams: ["JEE Main"], tags: ["Top NIT", "Core Engineering", "Placements"], overview: "A prestigious NIT with strong emphasis on core engineering and consistent industry partnerships.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 172000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 172000 }, { name: "B.Tech Civil Engineering", duration: "4 years", annualFees: 172000 }], recruiters: ["Microsoft", "Amazon", "Tata Motors", "Infosys"], reviews: [{ author: "Rajesh N.", role: "Student", rating: 4.5, year: 2025, comment: "Excellent faculty and strong placement support." }, { author: "Anjali M.", role: "Alumni", rating: 4.4, year: 2024, comment: "Steady placements and good academic environment." }] },
  { slug: "pec-chandigarh", name: "Punjab Engineering College, Chandigarh", location: "Chandigarh", state: "Chandigarh", ownership: "Public", feesAnnual: 95000, rating: 4.3, placementRate: 82, medianPackageLpa: 8.7, highestPackageLpa: 32, establishedYear: 1921, exams: ["JEE Main"], tags: ["Affordable", "Legacy", "North India"], overview: "India's oldest engineering college with strong legacy and affordable education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 95000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 95000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 95000 }], recruiters: ["TCS", "Infosys", "HCL", "Wipro"], reviews: [{ author: "Naveen S.", role: "Student", rating: 4.3, year: 2025, comment: "Historic institution with great value for money." }, { author: "Simran K.", role: "Alumni", rating: 4.2, year: 2024, comment: "Good academics and affordable compared to private colleges." }] },
  { slug: "iit-kanpur", name: "Indian Institute of Technology, Kanpur", location: "Kanpur", state: "Uttar Pradesh", ownership: "Public", feesAnnual: 180000, rating: 4.8, placementRate: 97, medianPackageLpa: 21.3, highestPackageLpa: 82, establishedYear: 1959, exams: ["JEE Main"], tags: ["Elite", "Research", "Placements"], overview: "A premier IIT known for strong research culture and excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Aerospace Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "Deloitte"], reviews: [{ author: "Abhishek V.", role: "Student", rating: 4.8, year: 2025, comment: "Strong research opportunities and excellent placements." }, { author: "Meera D.", role: "Alumni", rating: 4.8, year: 2024, comment: "Career-defining experience with global opportunities." }] },
  { slug: "amrita-vishwa-vidyapeetham", name: "Amrita Vishwa Vidyapeetham", location: "Coimbatore", state: "Tamil Nadu", ownership: "Private", feesAnnual: 280000, rating: 4.4, placementRate: 83, medianPackageLpa: 9.2, highestPackageLpa: 33, establishedYear: 1994, exams: ["AEEE", "JEE Main"], tags: ["Private", "Research", "Industry"], overview: "A spiritual university combining engineering excellence with holistic development.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 280000 }], recruiters: ["Infosys", "Cognizant", "IBM", "HCL"], reviews: [{ author: "Sanjay M.", role: "Student", rating: 4.4, year: 2025, comment: "Good academic environment with focus on holistic development." }, { author: "Divya R.", role: "Alumni", rating: 4.3, year: 2024, comment: "Placements are decent; culture emphasizes ethics and values." }] },
  { slug: "dcet-bengaluru", name: "Dayananda Sagar College of Engineering, Bengaluru", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 250000, rating: 4.2, placementRate: 81, medianPackageLpa: 8.8, highestPackageLpa: 30, establishedYear: 1979, exams: ["KCET", "COMEDK"], tags: ["Bangalore", "Affordable", "Private"], overview: "A reputable private college in Bangalore with solid academics and placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 250000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 250000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 250000 }], recruiters: ["TCS", "Infosys", "Accenture", "Wipro"], reviews: [{ author: "Rahul G.", role: "Student", rating: 4.2, year: 2025, comment: "Good placement support and reasonable fees for Bangalore." }, { author: "Neha P.", role: "Alumni", rating: 4.1, year: 2024, comment: "Steady growth in placements and good faculty." }] },
  { slug: "mnnit-allahabad", name: "Moti Lal Nehru National Institute of Technology, Allahabad", location: "Allahabad", state: "Uttar Pradesh", ownership: "Public", feesAnnual: 170000, rating: 4.4, placementRate: 84, medianPackageLpa: 9.5, highestPackageLpa: 34, establishedYear: 1961, exams: ["JEE Main"], tags: ["NIT", "Affordable", "Placements"], overview: "A prominent NIT offering quality engineering education at affordable costs.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 170000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 170000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 170000 }], recruiters: ["Microsoft", "Amazon", "Infosys", "TCS"], reviews: [{ author: "Vivek K.", role: "Student", rating: 4.4, year: 2025, comment: "Great value for money and good academics." }, { author: "Pooja S.", role: "Alumni", rating: 4.3, year: 2024, comment: "Solid placements and caring faculty." }] },
  { slug: "sairam-engineering", name: "Sairam Engineering College, Chennai", location: "Chennai", state: "Tamil Nadu", ownership: "Private", feesAnnual: 220000, rating: 4.1, placementRate: 78, medianPackageLpa: 7.9, highestPackageLpa: 29, establishedYear: 1997, exams: ["TNEA"], tags: ["Chennai", "Private", "Affordable"], overview: "A private engineering college with reasonable fees and steady placement records.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 220000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 220000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 220000 }], recruiters: ["Cognizant", "TCS", "Infosys", "HCL"], reviews: [{ author: "Pradeep K.", role: "Student", rating: 4.1, year: 2025, comment: "Good placement drive and reasonable fees." }, { author: "Ashok S.", role: "Alumni", rating: 4.0, year: 2024, comment: "Decent placements for a private college." }] },
  { slug: "iit-guwahati", name: "Indian Institute of Technology, Guwahati", location: "Guwahati", state: "Assam", ownership: "Public", feesAnnual: 180000, rating: 4.7, placementRate: 96, medianPackageLpa: 19.2, highestPackageLpa: 72, establishedYear: 1994, exams: ["JEE Main"], tags: ["Elite", "Northeast", "Research"], overview: "A premier IIT in Northeast India offering quality education and excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electronics Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Amazon", "Deloitte"], reviews: [{ author: "Ravi B.", role: "Student", rating: 4.7, year: 2025, comment: "Excellent placements and vibrant campus life." }, { author: "Sushma G.", role: "Alumni", rating: 4.6, year: 2024, comment: "Great academics and career opportunities." }] },
  { slug: "dtu-delhi", name: "Delhi Technological University", location: "Delhi", state: "Delhi", ownership: "Public", feesAnnual: 120000, rating: 4.3, placementRate: 86, medianPackageLpa: 9.1, highestPackageLpa: 35, establishedYear: 1941, exams: ["JEE Main"], tags: ["Delhi", "Affordable", "Placements"], overview: "A prestigious public university offering quality engineering education in New Delhi.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 120000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 120000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 120000 }], recruiters: ["TCS", "Infosys", "Amazon", "HCL"], reviews: [{ author: "Aman D.", role: "Student", rating: 4.3, year: 2025, comment: "Good college with decent placements and affordable fees." }, { author: "Nina M.", role: "Alumni", rating: 4.2, year: 2024, comment: "Strong alumni network and good academics." }] },
  { slug: "iit-madras", name: "Indian Institute of Technology, Madras", location: "Chennai", state: "Tamil Nadu", ownership: "Public", feesAnnual: 180000, rating: 4.9, placementRate: 98, medianPackageLpa: 23.1, highestPackageLpa: 85, establishedYear: 1959, exams: ["JEE Main"], tags: ["Elite", "Top placement", "Research"], overview: "One of India's top IITs with world-class infrastructure and exceptional placement records.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electronics Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "McKinsey"], reviews: [{ author: "Karan M.", role: "Student", rating: 4.9, year: 2025, comment: "Top-tier education and career opportunities." }, { author: "Lisa R.", role: "Alumni", rating: 4.9, year: 2024, comment: "Life-changing experience with global recognition." }] },
  { slug: "psg-coimbatore", name: "PSG College of Technology", location: "Coimbatore", state: "Tamil Nadu", ownership: "Private", feesAnnual: 290000, rating: 4.6, placementRate: 90, medianPackageLpa: 11.8, highestPackageLpa: 45, establishedYear: 1951, exams: ["TNEA", "Entrance"], tags: ["Premium", "Coimbatore", "Placements"], overview: "A premium private engineering college with strong industry connections and excellent infrastructure.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 290000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 290000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 290000 }], recruiters: ["Infosys", "TCS", "Cognizant", "Capgemini"], reviews: [{ author: "Tushar N.", role: "Student", rating: 4.6, year: 2025, comment: "Excellent placements and good faculty." }, { author: "Megha S.", role: "Alumni", rating: 4.5, year: 2024, comment: "Worth the fees; strong brand in Tamil Nadu." }] },
  { slug: "daiict-ahmedabad", name: "Dhirubhai Ambani Institute of Information and Communication Technology", location: "Ahmedabad", state: "Gujarat", ownership: "Private", feesAnnual: 380000, rating: 4.7, placementRate: 93, medianPackageLpa: 16.5, highestPackageLpa: 58, establishedYear: 2003, exams: ["DAEE", "Entrance"], tags: ["ICT", "Premium", "Placements"], overview: "A specialized institute for IT and communication technology with excellent placements.", courses: [{ name: "B.Tech Information and Communication Technology", duration: "4 years", annualFees: 380000 }, { name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 380000 }, { name: "M.Tech", duration: "2 years", annualFees: 220000 }], recruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs"], reviews: [{ author: "Akshay T.", role: "Student", rating: 4.7, year: 2025, comment: "Specialized focus on ICT with excellent placements." }, { author: "Nishant K.", role: "Alumni", rating: 4.6, year: 2024, comment: "Great for tech careers with strong industry connections." }] },
  { slug: "nit-srinagar", name: "National Institute of Technology, Srinagar", location: "Srinagar", state: "Jammu and Kashmir", ownership: "Public", feesAnnual: 165000, rating: 4.1, placementRate: 75, medianPackageLpa: 7.8, highestPackageLpa: 28, establishedYear: 1960, exams: ["JEE Main"], tags: ["NIT", "North India", "Affordable"], overview: "A NIT with developing infrastructure and growing industry presence.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 165000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 165000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 165000 }], recruiters: ["TCS", "Infosys", "HCL", "Tech Mahindra"], reviews: [{ author: "Sameer A.", role: "Student", rating: 4.1, year: 2025, comment: "Good academics but fewer placement opportunities." }, { author: "Asma K.", role: "Alumni", rating: 4.0, year: 2024, comment: "Beautiful location but slower growth in placements." }] },
  { slug: "thapar-university", name: "Thapar Institute of Engineering and Technology", location: "Patiala", state: "Punjab", ownership: "Private", feesAnnual: 320000, rating: 4.5, placementRate: 87, medianPackageLpa: 11.3, highestPackageLpa: 40, establishedYear: 1956, exams: ["JEE Main", "Entrance"], tags: ["Punjab", "Private", "Placements"], overview: "A well-established private engineering college with strong industry placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 320000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 320000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 320000 }], recruiters: ["Amazon", "Microsoft", "Google", "Cognizant"], reviews: [{ author: "Sahil J.", role: "Student", rating: 4.5, year: 2025, comment: "Good placements and strong faculty." }, { author: "Jasmeet K.", role: "Alumni", rating: 4.4, year: 2024, comment: "Solid choice for engineering education." }] },
  { slug: "nit-hamirpur", name: "National Institute of Technology, Hamirpur", location: "Hamirpur", state: "Himachal Pradesh", ownership: "Public", feesAnnual: 168000, rating: 4.2, placementRate: 80, medianPackageLpa: 8.5, highestPackageLpa: 31, establishedYear: 1986, exams: ["JEE Main"], tags: ["NIT", "Himalayas", "Affordable"], overview: "A NIT in a scenic location offering quality engineering education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 168000 }], recruiters: ["TCS", "Infosys", "Wipro", "Accenture"], reviews: [{ author: "Anand M.", role: "Student", rating: 4.2, year: 2025, comment: "Good campus life and decent placements." }, { author: "Priya H.", role: "Alumni", rating: 4.1, year: 2024, comment: "Great for those seeking peaceful academics away from metros." }] },
  { slug: "rvce-bangalore", name: "RVCE Bangalore", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 280000, rating: 4.5, placementRate: 88, medianPackageLpa: 10.2, highestPackageLpa: 35, establishedYear: 1963, exams: ["KCET"], tags: ["Bangalore", "Private", "Industry"], overview: "A reputable private college in Bangalore with strong industry connections.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 280000 }], recruiters: ["Amazon", "Cisco", "Intel", "Qualcomm"], reviews: [{ author: "Ananya B.", role: "Student", rating: 4.5, year: 2025, comment: "Great Bangalore advantage with good placements." }, { author: "Rohit S.", role: "Alumni", rating: 4.4, year: 2024, comment: "Strong network in IT industry." }] },
  { slug: "nmit-bangalore", name: "New Horizon College of Engineering", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 265000, rating: 4.3, placementRate: 83, medianPackageLpa: 9.5, highestPackageLpa: 32, establishedYear: 2002, exams: ["KCET"], tags: ["Bangalore", "Modern", "Private"], overview: "A modern private college offering quality engineering education in Bangalore.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 265000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 265000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 265000 }], recruiters: ["Cognizant", "TCS", "Infosys", "Flipkart"], reviews: [{ author: "Sanjana K.", role: "Student", rating: 4.3, year: 2025, comment: "Modern campus and reasonable placements." }, { author: "Varun M.", role: "Alumni", rating: 4.2, year: 2024, comment: "Good learning environment." }] },
  { slug: "iit-kharagpur", name: "Indian Institute of Technology, Kharagpur", location: "Kharagpur", state: "West Bengal", ownership: "Public", feesAnnual: 180000, rating: 4.8, placementRate: 97, medianPackageLpa: 20.5, highestPackageLpa: 78, establishedYear: 1951, exams: ["JEE Main"], tags: ["Elite", "Oldest IIT", "Research"], overview: "India's first IIT with excellent academics, research, and placement opportunities.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "Apple"], reviews: [{ author: "Arjun K.", role: "Student", rating: 4.8, year: 2025, comment: "Historic IIT with world-class facilities." }, { author: "Deepika R.", role: "Alumni", rating: 4.7, year: 2024, comment: "Strong legacy and excellent career outcomes." }] },
  { slug: "cbit-hyderabad", name: "CBIT Hyderabad", location: "Hyderabad", state: "Telangana", ownership: "Private", feesAnnual: 310000, rating: 4.4, placementRate: 86, medianPackageLpa: 10.8, highestPackageLpa: 39, establishedYear: 1997, exams: ["EAMCET"], tags: ["Hyderabad", "Private", "Placements"], overview: "A reputable private engineering college in Hyderabad with good industry placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 310000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 310000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 310000 }], recruiters: ["Microsoft", "Amazon", "Google", "TCS"], reviews: [{ author: "Vivek R.", role: "Student", rating: 4.4, year: 2025, comment: "Strong placement and good academic environment." }, { author: "Harshita V.", role: "Alumni", rating: 4.3, year: 2024, comment: "Good college for IT placements." }] },
  { slug: "ktu-kochi", name: "Cochin University of Science and Technology", location: "Kochi", state: "Kerala", ownership: "Public", feesAnnual: 110000, rating: 4.2, placementRate: 79, medianPackageLpa: 8.3, highestPackageLpa: 30, establishedYear: 1971, exams: ["KEAM"], tags: ["Kerala", "Affordable", "Public"], overview: "A public university in Kerala offering affordable engineering education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 110000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 110000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 110000 }], recruiters: ["TCS", "Infosys", "HCL", "Wipro"], reviews: [{ author: "Akshay V.", role: "Student", rating: 4.2, year: 2025, comment: "Good value for money in Kerala." }, { author: "Anjali M.", role: "Alumni", rating: 4.1, year: 2024, comment: "Solid education at very reasonable fees." }] },
  { slug: "sahrdaya-kochi", name: "Sahrdaya College of Engineering, Kochi", location: "Kochi", state: "Kerala", ownership: "Private", feesAnnual: 230000, rating: 4.1, placementRate: 77, medianPackageLpa: 7.9, highestPackageLpa: 28, establishedYear: 2002, exams: ["KEAM"], tags: ["Kerala", "Private", "Modern"], overview: "A private engineering college in Kerala with focus on industry-relevant education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 230000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 230000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 230000 }], recruiters: ["Cognizant", "Infosys", "TCS", "HCL"], reviews: [{ author: "Rajeev K.", role: "Student", rating: 4.1, year: 2025, comment: "Good infrastructure and decent placements." }, { author: "Meera S.", role: "Alumni", rating: 4.0, year: 2024, comment: "Reasonable fees with good learning environment." }] },
  { slug: "srmist-delhi", name: "SRM IST, Delhi", location: "Delhi", state: "Delhi", ownership: "Private", feesAnnual: 380000, rating: 4.3, placementRate: 81, medianPackageLpa: 9.6, highestPackageLpa: 36, establishedYear: 2016, exams: ["SRMJEEE"], tags: ["Delhi", "Premium", "New"], overview: "A new campus of SRM in Delhi offering quality engineering education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 380000 }, { name: "B.Tech Artificial Intelligence and Machine Learning", duration: "4 years", annualFees: 385000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 380000 }], recruiters: ["Amazon", "Microsoft", "Google", "Deloitte"], reviews: [{ author: "Karun M.", role: "Student", rating: 4.3, year: 2025, comment: "New campus with modern facilities." }, { author: "Shivam R.", role: "Alumni", rating: 4.2, year: 2024, comment: "Growing placements with good Delhi advantage." }] },
  { slug: "vit-pune", name: "VIT Pune", location: "Pune", state: "Maharashtra", ownership: "Private", feesAnnual: 280000, rating: 4.4, placementRate: 84, medianPackageLpa: 10.0, highestPackageLpa: 37, establishedYear: 2015, exams: ["VITEEE"], tags: ["Pune", "Private", "Modern"], overview: "A VIT campus in Pune with modern infrastructure and growing placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 280000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 280000 }], recruiters: ["Cognizant", "TCS", "Infosys", "Capgemini"], reviews: [{ author: "Pratik S.", role: "Student", rating: 4.4, year: 2025, comment: "Good campus in Pune with decent placements." }, { author: "Shruti K.", role: "Alumni", rating: 4.3, year: 2024, comment: "Growing institution with improving placements." }] },
  { slug: "coep-pune", name: "College of Engineering Pune", location: "Pune", state: "Maharashtra", ownership: "Public", feesAnnual: 145000, rating: 4.5, placementRate: 88, medianPackageLpa: 11.2, highestPackageLpa: 42, establishedYear: 1854, exams: ["JEE Main", "GATE"], tags: ["Pune", "Legacy", "Affordable"], overview: "India's oldest engineering college with strong academics and excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 145000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 145000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 145000 }], recruiters: ["Microsoft", "Amazon", "Google", "Deloitte"], reviews: [{ author: "Nikhil K.", role: "Student", rating: 4.5, year: 2025, comment: "Historic institution with excellent placements." }, { author: "Pooja G.", role: "Alumni", rating: 4.4, year: 2024, comment: "Strong legacy and great academic environment." }] },
  { slug: "fcrit-vashi", name: "Fr. C. Rodrigues Institute of Technology, Navi Mumbai", location: "Navi Mumbai", state: "Maharashtra", ownership: "Private", feesAnnual: 320000, rating: 4.3, placementRate: 82, medianPackageLpa: 9.3, highestPackageLpa: 34, establishedYear: 2000, exams: ["CET"], tags: ["Navi Mumbai", "Private", "Placements"], overview: "A private engineering college with good academic environment and placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 320000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 320000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 320000 }], recruiters: ["TCS", "Infosys", "Cognizant", "Accenture"], reviews: [{ author: "Sameer T.", role: "Student", rating: 4.3, year: 2025, comment: "Good placements near Mumbai." }, { author: "Anagha S.", role: "Alumni", rating: 4.2, year: 2024, comment: "Reasonable fees with decent job opportunities." }] },
  { slug: "mitaoe-pune", name: "MIT Academy of Engineering, Pune", location: "Pune", state: "Maharashtra", ownership: "Private", feesAnnual: 300000, rating: 4.4, placementRate: 85, medianPackageLpa: 10.5, highestPackageLpa: 38, establishedYear: 1989, exams: ["CET"], tags: ["Pune", "Private", "Industry"], overview: "A well-established private college in Pune with strong industry placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 300000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 300000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 300000 }], recruiters: ["Amazon", "Microsoft", "Infosys", "TCS"], reviews: [{ author: "Vedant M.", role: "Student", rating: 4.4, year: 2025, comment: "Great placements and good academic support." }, { author: "Tara K.", role: "Alumni", rating: 4.3, year: 2024, comment: "Strong choice for engineering education." }] },
  { slug: "nsit-delhi", name: "Netaji Subhas University of Technology, Delhi", location: "Delhi", state: "Delhi", ownership: "Public", feesAnnual: 125000, rating: 4.4, placementRate: 87, medianPackageLpa: 10.4, highestPackageLpa: 38, establishedYear: 1983, exams: ["JEE Main"], tags: ["Delhi", "Public", "Affordable"], overview: "A premier public engineering university in Delhi with excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 125000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 125000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 125000 }], recruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs"], reviews: [{ author: "Vikram D.", role: "Student", rating: 4.4, year: 2025, comment: "Excellent placements with affordable fees." }, { author: "Priya M.", role: "Alumni", rating: 4.3, year: 2024, comment: "One of the best public colleges in Delhi." }] },
  { slug: "iit-roorkee", name: "Indian Institute of Technology, Roorkee", location: "Roorkee", state: "Uttarakhand", ownership: "Public", feesAnnual: 180000, rating: 4.6, placementRate: 94, medianPackageLpa: 18.9, highestPackageLpa: 70, establishedYear: 1852, exams: ["JEE Main"], tags: ["Elite", "Oldest IIT", "Research"], overview: "India's oldest engineering institution with strong research and excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Civil Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "Deloitte"], reviews: [{ author: "Aditya K.", role: "Student", rating: 4.6, year: 2025, comment: "Historic IIT with excellent academics and placements." }, { author: "Naina S.", role: "Alumni", rating: 4.5, year: 2024, comment: "World-class institution with strong legacy." }] },
  { slug: "jec-jabalpur", name: "Jabalpur Engineering College", location: "Jabalpur", state: "Madhya Pradesh", ownership: "Public", feesAnnual: 138000, rating: 4.1, placementRate: 78, medianPackageLpa: 7.8, highestPackageLpa: 29, establishedYear: 1956, exams: ["JEE Main"], tags: ["Affordable", "Public", "MP"], overview: "A public engineering college in Madhya Pradesh offering quality education at affordable cost.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 138000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 138000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 138000 }], recruiters: ["TCS", "Infosys", "Wipro", "HCL"], reviews: [{ author: "Rahul T.", role: "Student", rating: 4.1, year: 2025, comment: "Good value college with reasonable placements." }, { author: "Shruti M.", role: "Alumni", rating: 4.0, year: 2024, comment: "Decent college for affordable engineering education." }] },
  { slug: "mec-bengaluru", name: "M.S. Ramaiah College of Engineering", location: "Bengaluru", state: "Karnataka", ownership: "Private", feesAnnual: 290000, rating: 4.5, placementRate: 86, medianPackageLpa: 10.7, highestPackageLpa: 39, establishedYear: 1962, exams: ["KCET"], tags: ["Bangalore", "Private", "Established"], overview: "An established private college in Bangalore with strong academics and placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 290000 }, { name: "B.Tech Information Technology", duration: "4 years", annualFees: 290000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 290000 }], recruiters: ["Amazon", "Cisco", "Intel", "SAP"], reviews: [{ author: "Siddharth L.", role: "Student", rating: 4.5, year: 2025, comment: "Strong placements with good Bangalore network." }, { author: "Aravind M.", role: "Alumni", rating: 4.4, year: 2024, comment: "Solid college with good career outcomes." }] },
  { slug: "ucce-visvesvaraya", name: "University Visvesvaraya College of Engineering", location: "Bengaluru", state: "Karnataka", ownership: "Public", feesAnnual: 95000, rating: 4.3, placementRate: 83, medianPackageLpa: 9.2, highestPackageLpa: 33, establishedYear: 1917, exams: ["KCET"], tags: ["Bangalore", "Affordable", "Oldest"], overview: "A historic and affordable public engineering college in Bangalore with good placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 95000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 95000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 95000 }], recruiters: ["TCS", "Infosys", "Cisco", "Amazon"], reviews: [{ author: "Harish B.", role: "Student", rating: 4.3, year: 2025, comment: "Great value in Bangalore with good academics." }, { author: "Anita K.", role: "Alumni", rating: 4.2, year: 2024, comment: "Historic college with strong network in tech." }] },
  { slug: "gecg-lucknow", name: "Dr. B.R. Ambedkar National Institute of Technology, Jalandhar", location: "Jalandhar", state: "Punjab", ownership: "Public", feesAnnual: 170000, rating: 4.3, placementRate: 82, medianPackageLpa: 9.1, highestPackageLpa: 33, establishedYear: 1987, exams: ["JEE Main"], tags: ["NIT", "Punjab", "Affordable"], overview: "A prominent NIT offering quality engineering education in Punjab.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 170000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 170000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 170000 }], recruiters: ["Microsoft", "Amazon", "Infosys", "TCS"], reviews: [{ author: "Balpreet S.", role: "Student", rating: 4.3, year: 2025, comment: "Good NIT with decent placements." }, { author: "Gurpreet K.", role: "Alumni", rating: 4.2, year: 2024, comment: "Strong academics and fair placement support." }] },
  { slug: "nit-silchar", name: "National Institute of Technology, Silchar", location: "Silchar", state: "Assam", ownership: "Public", feesAnnual: 165000, rating: 4.0, placementRate: 76, medianPackageLpa: 7.5, highestPackageLpa: 27, establishedYear: 1967, exams: ["JEE Main"], tags: ["NIT", "Northeast", "Affordable"], overview: "A NIT in Northeast India offering engineering education at reasonable cost.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 165000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 165000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 165000 }], recruiters: ["TCS", "Infosys", "HCL", "Wipro"], reviews: [{ author: "Soumik D.", role: "Student", rating: 4.0, year: 2025, comment: "Good education with growing placements." }, { author: "Ritika M.", role: "Alumni", rating: 3.9, year: 2024, comment: "Decent college for students from Northeast." }] },
  { slug: "nit-durgapur", name: "National Institute of Technology, Durgapur", location: "Durgapur", state: "West Bengal", ownership: "Public", feesAnnual: 172000, rating: 4.2, placementRate: 79, medianPackageLpa: 8.3, highestPackageLpa: 30, establishedYear: 1960, exams: ["JEE Main"], tags: ["NIT", "WB", "Affordable"], overview: "A NIT with growing infrastructure and improving placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 172000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 172000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 172000 }], recruiters: ["Microsoft", "Amazon", "Infosys", "TCS"], reviews: [{ author: "Ajoy R.", role: "Student", rating: 4.2, year: 2025, comment: "Good campus with steady placements." }, { author: "Priya B.", role: "Alumni", rating: 4.1, year: 2024, comment: "Solid engineering education." }] },
  { slug: "nit-patna", name: "National Institute of Technology, Patna", location: "Patna", state: "Bihar", ownership: "Public", feesAnnual: 168000, rating: 4.1, placementRate: 77, medianPackageLpa: 7.9, highestPackageLpa: 28, establishedYear: 1886, exams: ["JEE Main"], tags: ["NIT", "Bihar", "Historic"], overview: "A historic NIT offering quality engineering education.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 168000 }, { name: "B.Tech Civil Engineering", duration: "4 years", annualFees: 168000 }], recruiters: ["TCS", "Infosys", "Accenture", "Cognizant"], reviews: [{ author: "Anand K.", role: "Student", rating: 4.1, year: 2025, comment: "Steady placements and good academics." }, { author: "Radha S.", role: "Alumni", rating: 4.0, year: 2024, comment: "Good institution for engineering education." }] },
  { slug: "iit-indore", name: "Indian Institute of Technology, Indore", location: "Indore", state: "Madhya Pradesh", ownership: "Public", feesAnnual: 180000, rating: 4.4, placementRate: 89, medianPackageLpa: 14.2, highestPackageLpa: 52, establishedYear: 2009, exams: ["JEE Main"], tags: ["IIT", "New", "Growing"], overview: "A newer IIT with modern infrastructure and growing placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electrical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Amazon", "Goldman Sachs"], reviews: [{ author: "Arjun S.", role: "Student", rating: 4.4, year: 2025, comment: "New campus with excellent infrastructure." }, { author: "Sarita M.", role: "Alumni", rating: 4.3, year: 2024, comment: "Growing IIT with good placements." }] },
  { slug: "iit-varanasi", name: "Indian Institute of Technology, Varanasi (BHU)", location: "Varanasi", state: "Uttar Pradesh", ownership: "Public", feesAnnual: 180000, rating: 4.5, placementRate: 91, medianPackageLpa: 16.8, highestPackageLpa: 61, establishedYear: 1919, exams: ["JEE Main"], tags: ["Elite", "Historic IIT", "Research"], overview: "A prestigious IIT with rich heritage and excellent research culture.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Civil Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Goldman Sachs", "Adobe"], reviews: [{ author: "Vikram N.", role: "Student", rating: 4.5, year: 2025, comment: "Prestigious IIT with excellent academics." }, { author: "Neha R.", role: "Alumni", rating: 4.4, year: 2024, comment: "Strong brand and good placements." }] },
  { slug: "iit-bhu", name: "Indian Institute of Technology, BHU Delhi", location: "Delhi", state: "Delhi", ownership: "Public", feesAnnual: 180000, rating: 4.6, placementRate: 93, medianPackageLpa: 19.5, highestPackageLpa: 72, establishedYear: 2016, exams: ["JEE Main"], tags: ["Elite", "Delhi", "New campus"], overview: "A new campus of IIT BHU in Delhi with world-class facilities and excellent placements.", courses: [{ name: "B.Tech Computer Science and Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Electronics and Communication Engineering", duration: "4 years", annualFees: 180000 }, { name: "B.Tech Mechanical Engineering", duration: "4 years", annualFees: 180000 }], recruiters: ["Google", "Microsoft", "Amazon", "McKinsey"], reviews: [{ author: "Yash M.", role: "Student", rating: 4.6, year: 2025, comment: "New campus with Delhi advantage and top recruiters." }, { author: "Priya V.", role: "Alumni", rating: 4.5, year: 2024, comment: "Excellent opportunities in the capital city." }] },
];


export function formatINR(value: number): string {
  return new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
}

export function findCollegeBySlug(slug: string): College | undefined {
  return colleges.find((college) => college.slug === slug);
}

export function filterColleges(query: CollegeQuery): College[] {
  const search = query.search?.trim().toLowerCase();
  const location = query.location?.trim().toLowerCase();
  const course = query.course?.trim().toLowerCase();
  const maxFees = query.maxFees;

  return colleges.filter((college) => {
    const matchesSearch = !search || college.name.toLowerCase().includes(search);
    const matchesLocation = !location || college.location.toLowerCase() === location;
    const matchesCourse =
      !course ||
      college.courses.some((item) => item.name.toLowerCase().includes(course));
    const matchesFees = typeof maxFees !== "number" || college.feesAnnual <= maxFees;

    return matchesSearch && matchesLocation && matchesCourse && matchesFees;
  });
}

export function paginateColleges(collegeList: College[], page = 1, limit = 6) {
  const safePage = Math.max(1, page);
  const safeLimit = Math.max(1, limit);
  const start = (safePage - 1) * safeLimit;
  return {
    items: collegeList.slice(start, start + safeLimit),
    page: safePage,
    limit: safeLimit,
    total: collegeList.length,
    totalPages: Math.max(1, Math.ceil(collegeList.length / safeLimit)),
  };
}

export function compareColleges(slugs: string[]): College[] {
  const uniqueSlugs = [...new Set(slugs)].slice(0, 3);
  return uniqueSlugs.map((slug) => findCollegeBySlug(slug)).filter(Boolean) as College[];
}
